services:
  simulator:
    image: dascr/loadp:latest
    container_name: simulator
    ports:
      - "8080:8080"
  activemq:
    build: ./amq_service
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
  actuator_service:
    build: ./actuator_service
    container_name: actuator_service
    ports:
      - "8000:8000"
    environment:
      ARTEMIS_HOST: activemq
      ARTEMIS_PORT: 61616
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
    depends_on:
      - activemq
      - simulator
  converter:
    build: ./converter_service
    container_name: converter
    depends_on:
      - activemq
    environment:
      AMQ_HOST: activemq
      AMQ_PORT: 61616
      BACKEND_URL: http://host.docker.internal:8080
      LOG_LEVEL: INFO
