services:
  simulator:
    image: docker.io/dascr/loadp:latest
    container_name: simulator
    ports:
      - "8080:8080"

  redis:
    image: docker.io/redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  activemq:
    build: ./amq_service
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8161/console" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin

  cache_service:
    build: ./cache_service
    container_name: cache_service
    ports:
      - "8081:8080"
    environment:
      ARTEMIS_HOST: activemq
      ARTEMIS_PORT: 61616
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/docs" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      activemq:
        condition: service_healthy
      simulator:
        condition: service_started
      redis:
        condition: service_healthy
  metrics_service:
    build: ./metrics_service
    container_name: metrics_service
    ports:
      - "8082:8080"
    environment:
      ARTEMIS_HOST: activemq
      ARTEMIS_PORT: 61616
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
      CACHE_URL: http://cache_service:8080
    depends_on:
      activemq:
        condition: service_healthy
      cache_service:
        condition: service_started

  actuator_service:
    build: ./actuator_service
    container_name: actuator_service
    ports:
      - "8083:8080"
    environment:
      ARTEMIS_HOST: activemq
      ARTEMIS_PORT: 61616
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
      CACHE_URL: http://cache_service:8080
    depends_on:
      activemq:
        condition: service_healthy
      cache_service:
        condition: service_started

  converter:
    build: ./converter_service
    container_name: converter
    depends_on:
      actuator_service:
        condition: service_started
      activemq:
        condition: service_healthy
    environment:
      AMQ_HOST: activemq
      AMQ_PORT: 61616
      BACKEND_URL: http://simulator:8080
      LOG_LEVEL: INFO

  automation-rules:
    build:
      context: .
      dockerfile: automation-rules/Dockerfile
    container_name: automation-rules
    depends_on:
      activemq:
        condition: service_healthy
    volumes:
      - automation_rules_data:/data
    ports:
      - "8084:8080"

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      metrics_service:
        condition: service_started
      actuator_service:
        condition: service_started
    ports:
      - "8085:80"

volumes:
  automation_rules_data:
